[profile.default]
evm_version = "cancun"
ffi = true
fs_permissions = [{access = "read-write", path = ".forge-snapshots/"}]
libs = ["lib"]
out = "out"
solc_version = "0.8.25"
optimizer_runs = 200
src = "src"
via-ir = true

[profile.lint]
exclude_lints = ["screaming-snake-case-immutable", "screaming-snake-case-const"]

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
